services:
  - type: web
    name: eventure
    env: node
    buildCommand: npm install && npm run build:css
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false